### ISSUE TITLE
RIS conversion, issued date output

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc-citeproc#229] opened 2016-05-20 19:23 UTC
I have this RIS format citation. Notice that the date has all the information, year, month and date. I run it through `pandoc-citeproc` using `pandoc-citeproc -y -f ris <~/Downloads/nejmoa1307491.ris`. The output is OK but there is one bit that I think could be better. It is the issued date which comes out as this:

~~~~
  issued:
  - year: '2014'
    month: Mar
    day: '27'
~~~~

While the above is correct, it is inconvenient. **It would be a lot more convenient for it to be output using `date-parts` and just the numeric month** so that when the reference is output in my Czech documents the month comes out correctly and not as "Mar".

----
RIS citation record:
~~~~



TY  - JOUR
T1  - Patches of Disorganization in the Neocortex of Children with Autism
AU  - Stoner, Rich
AU  - Chow, Maggie L.
AU  - Boyle, Maureen P.
AU  - Sunkin, Susan M.
AU  - Mouton, Peter R.
AU  - Roy, Subhojit
AU  - Wynshaw-Boris, Anthony
AU  - Colamarino, Sophia A.
AU  - Lein, Ed S.
AU  - Courchesne, Eric
Y1  - 2014/03/26
PY  - 2014
DA  - 2014/03/27
N1  - doi: 10.1056/NEJMoa1307491
DO  - 10.1056/NEJMoa1307491
T2  - New England Journal of Medicine
JF  - New England Journal of Medicine
JO  - N Engl J Med
SP  - 1209
EP  - 1219
VL  - 370
IS  - 13
PB  - Massachusetts Medical Society
SN  - 0028-4793
M3  - doi: 10.1056/NEJMoa1307491
UR  - http://dx.doi.org/10.1056/NEJMoa1307491
Y2  - 2016/05/20
ER  - 
~~~~

**Comment by jgm** [comment] 2016-05-22 16:34
Conversion from ris is handled by the bibutils library
(wrapped in bibutils-hs), so you should direct your inquiry
there.

+++ Václav Haisman [May 20 16 12:23 ]:

**Comment by nickbart1980** [comment] 2016-05-23 08:22
I don’t think this is a bibutils issue. While pandoc-citeproc does use bibutils to convert RIS and other formats to MODS first, the MODS → CSL JSON (or MODS → CSL YAML) conversion is done by pandoc-citeproc itself; bibutils knows nothing about CSL JSON/YAML and its date formats.

Indeed, `month: Mar` is not being localised eventually, and, since pandoc-citeproc’s CSL YAML is based on CSL JSON, and CSL JSON permits numbers only in its array format for dates, arguably incorrect.

What’s more, JSON output from the OP’s RIS data (`pandoc-citeproc -j issue229.ris`) contains an *empty* `issued` element; that’s clearly a bug:

~~~
[
  {
    "DOI": "10.1056/NEJMoa1307491",
    "ISSN": "0028-4793",
    "URL": "http://dx.doi.org/10.1056/NEJMoa1307491",
    "author": [
      {
        "family": "Stoner",
        "given": "Rich"
      },
      {
        "family": "Chow",
        "given": "Maggie L."
      },
      {
        "family": "Boyle",
        "given": "Maureen P."
      },
      {
        "family": "Sunkin",
        "given": "Susan M."
      },
      {
        "family": "Mouton",
        "given": "Peter R."
      },
      {
        "family": "Roy",
        "given": "Subhojit"
      },
      {
        "family": "Wynshaw-Boris",
        "given": "Anthony"
      },
      {
        "family": "Colamarino",
        "given": "Sophia A."
      },
      {
        "family": "Lein",
        "given": "Ed S."
      },
      {
        "family": "Courchesne",
        "given": "Eric"
      }
    ],
    "container-title": "New England Journal of Medicine",
    "id": "Stoner2014",
    "issue": "13",
    "issued": {},
    "page": "1209-1219",
    "publisher": "Massachusetts Medical Society",
    "title": "Patches of disorganization in the neocortex of children with autism",
    "type": "article-journal",
    "volume": "370"
  }
]
~~~

Finally: I had to test this with pandoc-citeproc 0.9.1.1 installed with homebrew, as pandoc-citeproc installed from the latest source via stack did not recognise .ris or .mods (the homebrew version does). Is this a known issue, or can you reproduce this?

**Comment by wilx** [comment] 2016-05-23 14:13
> did not recognise .ris

I have updated and now `pandoc-citeproc` does not recognize RIS either.

**Comment by wilx** [comment] 2016-05-23 14:51
Funnelling the RIS record through bibutils 5.7 `ris2xml` gets me `<dateIssued>2014-03-27</dateIssued>`.

**Comment by jgm** [comment] 2016-05-23 17:31
+++ Václav Haisman [May 23 16 07:13 ]:
>     did not recognise .ris
>
>   I have updated and now pandoc-citeproc does not recognize RIS either.

Updated from where?  If you build with cabal or stack, you
need to make sure the hsbibutils flag is set (the default)
or .ris won't be supported.

Or did you use the binary package?

**Comment by wilx** [comment] 2016-05-23 19:22
On 23.5.2016 19:31, John MacFarlane wrote:
> +++ Václav Haisman [May 23 16 07:13 ]:
>> did not recognise .ris
>>
>> I have updated and now pandoc-citeproc does not recognize RIS either.
> 
> Updated from where? If you build with cabal or stack, you
> need to make sure the hsbibutils flag is set (the default)
> or .ris won't be supported.
> 
> Or did you use the binary package?

I was not able to build with RIS support from sources even with the
flag, somehow. But I am not very experienced with Cabal so I think it is
probably my fault. Never mind this, I am more interested in the OP issue. :)

-- 
VH

**Comment by jgm** [comment] 2016-05-24 04:29
Pandoc-citeproc uses bibutils to convert the source format to bibtex, then uses its native bibtex reader to convert that to a list of References.

bibutils `ris2xml | xml2bib` yields:
```
@Article{Stoner2014,
author="Stoner, Rich
and Chow, Maggie L.
and Boyle, Maureen P.
and Sunkin, Susan M.
and Mouton, Peter R.
and Roy, Subhojit
and Wynshaw-Boris, Anthony
and Colamarino, Sophia A.
and Lein, Ed S.
and Courchesne, Eric",
title="Patches of Disorganization in the Neocortex of Children with Autism",
journal="New England Journal of Medicine",
year="2014",
month="Mar",
day="27",
publisher="Massachusetts Medical Society",
volume="370",
number="13",
pages="1209--1219",
issn="0028-4793",
doi="10.1056/NEJMoa1307491",
url="http://dx.doi.org/10.1056/NEJMoa1307491"
}
```
So, that is where the `Mar` is being introduced.
I think I see now why it's not being converted to a proper numerical date (the parser is expecting `mar` not `Mar`).  If that's it, it's easily fixed.

**Comment by wilx** [comment] 2016-05-24 05:22
I took a look at the source and it seemed to me that the implementations for `ToYaml` and `ToJSON` type classed in `Reference.hs` are a bit dissimilar beyond the necessary bits. There is `instance ToYaml RefDate` but it does not produce `date-parts`. Then there is missing `instance ToYaml [RefDate]` but `instance ToJSON [RefDate]` does exist and does mention `date-parts`. I thought this might be what is missing or needs to be fixed. But I cannot really tell because my Haskell-fu is really weak.

**Comment by jgm** [comment] 2016-05-24 05:41
The differences are intentional.  ToYaml targets pandoc YAML
metadata representation of the reference; ToJSON tries to
produce standard CSL JSON.

+++ Václav Haisman [May 23 16 22:22 ]:

**Comment by jgm** [comment] 2016-05-24 05:44
Commit 7f96d11959940644b52933778d2b3046304dce01 fixes the treatment of the issued date.
Now we get in YAML
```
  issued:
  - year: '2014'
    month: '3'
    day: '27'
```
and in JSON:
```
    "issued": {
      "date-parts": [
        [
          2014,
          3,
          27
        ]
      ]
    },
```

**Closed** 2016-05-24 05:44 UTC
