### ISSUE TITLE
Hypertraget + List of citation references too long for LaTeX

### ISSUE THREAD

**Issue by hugoroy** [jgm/pandoc-citeproc#264] opened 2016-11-01 12:30 UTC
(This looks more like a bug with the hyperref's package hypertarget command, but I believe it's probably easier to fix here than in hyperref :-)

Basically, if I have too many references, LaTeX will try to put all of them on one page instead of breaking to several pages if necessary. This results in an overfull vbox because 1 page is not big enough.

(I will try to provide an exemple as I can't share the files I was working on - let me know if you can't reproduce)

**Comment by wilx** [comment] 2016-11-03 09:00
It would help a lot if you had a test case, I think.

**Comment by hugoroy** [comment] 2016-11-05 17:15
I realised the problem is actually when used in conjunction with  \widowpenalty10000 and  \clubpenalty10000 which are used to mitigate the sometimes very strange way of Latex to leave an orphan word or on a whole page.


[case-csl.txt](https://github.com/jgm/pandoc-citeproc/files/573363/case-csl.txt)
[references-yaml.txt](https://github.com/jgm/pandoc-citeproc/files/573364/references-yaml.txt)
[sample-markdown.txt](https://github.com/jgm/pandoc-citeproc/files/573365/sample-markdown.txt)

But I think this illustrates that the way the references are generated into latex by pandoc is not optimal.

**Comment by jgm** [comment] 2016-11-05 21:13
I think the problem is these windowpenalty and clubpenalty settings you're using.
I don't see anything specific that could be done better with the way we're generating references, so I'm closing this unless you  have specific suggestions.

**Closed by jgm** 2016-11-05 21:13 UTC
