### ISSUE TITLE
`display="block"` in CSL style is not respected in LaTeX output

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc-citeproc#261] opened 2016-10-23 14:51 UTC
With the test document below and `apa-annotated-bibliography.csl` style, the abstract of the citation is not separated from the previous part of the citation. The URL is directly followed, without any space or new line, etc., by the first letter in the abstract. The LaTeX rendering looks like this:

``` latex
...\url{https://doi.org/10.1001/jamacardio.2016.3312}P values and...
```

I initially thought this was an issue with the style itself and I have attempted to patch it (https://github.com/citation-style-language/styles/pull/2277) but I was told this was rather a CSL processor issue. It seems that `pandoc-citeproc` needs to recognize and handle `display="block"` attribute of `<text>` in CSL style.

Test document:

``` markdown

---
csl: apa-annotated-bibliography.csl
references:
- id: Mark2016
  type: article-journal
  author:
  - family: Mark
    given: Daniel B.
  - family: Lee
    given: Kerry L.
  - family: Harrell
    given: Frank E.
    suffix: Jr.
  issued:
  - year: '2016'
    month: '10'
    day: '12'
  title: Understanding the role of p values and hypothesis tests in clinical research
  container-title: JAMA Cardiology
  abstract: P values and hypothesis testing methods are frequently misused in clinical
    research. Much of this misuse appears to be owing to the widespread, mistaken
    belief that they provide simple, reliable, and objective triage tools for separating
    the true and important from the untrue or unimportant. The primary focus in interpreting
    therapeutic clinical research data should be on the treatment (“oomph”) effect,
    a metaphorical force that moves patients given an effective treatment to a different
    clinical state relative to their control counterparts. This effect is assessed
    using 2 complementary types of statistical measures calculated from the data,
    namely, effect magnitude or size and precision of the effect size. In a randomized
    trial, effect size is often summarized using constructs, such as odds ratios,
    hazard ratios, relative risks, or adverse event rate differences. How large a
    treatment effect has to be to be consequential is a matter for clinical judgment.
    The precision of the effect size (conceptually related to the amount of spread
    in the data) is usually addressed with confidence intervals. P values (significance
    tests) were first proposed as an informal heuristic to help assess how “unexpected”
    the observed effect size was if the true state of nature was no effect or no difference.
    Hypothesis testing was a modification of the significance test approach that envisioned
    controlling the false-positive rate of study results over many (hypothetical)
    repetitions of the experiment of interest. Both can be helpful but, by themselves,
    provide only a tunnel vision perspective on study results that ignores the clinical
    effects the study was conducted to measure.
  URL: http://dx.doi.org/10.1001/jamacardio.2016.3312
  DOI: 10.1001/jamacardio.2016.3312
  ISSN: '2380-6583'
...

# Text

This and that is said in @Mark2016. Another sentence here.

# References
```

I have used `pandoc --verbose  --filter pandoc-citeproc -f markdown -t latex -o test-citeproc.pdf test-citeproc.md` to process it.

**Comment by rmzelle** [comment] 2016-10-23 21:50
(mostly a duplicate of https://github.com/jgm/pandoc-citeproc/issues/85 )

**Closed** 2021-04-29 22:00 UTC
