### ISSUE TITLE
"@ref-id" form (as opposed to [@ref-id] form) isn't shedding parentheses as expected.

### ISSUE THREAD

**Issue by sanchom** [jgm/pandoc-citeproc#343] opened 2018-07-19 16:10 UTC
My bibliography file:

```
---
references:
- id: hayes
  type: legal_case
  title: 'Hayes v British Columbia Television Broadcasting System Ltd'
  title-short: Hayes
  issued:
  - year: 1992
  authority: '74 BCLR (2d) 120 (CA)'

- id: sproule
  type: legal_case
  title: 'Sproule v McConnell'
  title-short: Sproule
  authority: '[1925] 1 DLR 982 (Sask CA)'
...
```

A minimal .csl:

```
<?xml version="1.0" encoding="utf-8"?>
<style xmlns="http://purl.org/net/xbiblio/csl" class="in-text" version="1.0">
  <info>
    <title>Allard Law Citation Style (in-text)</title>
    <link href="http://guides.library.ubc.ca/legalcitation/home" rel="documentation"/>
    <category citation-format="label"/>
    <category field="law"/>
  </info>
  <locale xml:lang="en">
  </locale>
  <citation>
    <layout prefix="(" suffix=")" delimiter="; ">
      <choose>
        <if position="ibid">
          <text term="ibid" font-style="italic" strip-periods="true"/>
        </if>
        <else-if position="subsequent">
          <group delimiter=" ">
            <text variable="title-short" font-style="italic"/>
          </group>
        </else-if>
        <else>
          <group delimiter=" ">
            <group delimiter=" " suffix=",">
              <text variable="title" font-style="italic"/>
              <group prefix="(" suffix=")">
                <date variable="issued">
                  <date-part name="year"/>
                </date>
              </group>
            </group>
            <text variable="authority"/>
            <group prefix="[" suffix="]">
              <text variable="title-short" font-style="italic"/>
            </group>
          </group>
        </else>
      </choose>
    </layout>
  </citation>
</style>
```

Sample markdown input:

```
---
suppress-bibliography: true
---

The leading case in B.C. on the general test for the existence of a
partnership is that of @hayes. In determining whether a partnership
has formed, the meaning of the words "carrying on business in common
with a view of profit" should be considered [@hayes].

The parties must intend a partnership to form [@sproule]. The analysis
used to discern the intention of the parties is two-pronged. A court
will first review the agreement between the parties, then will look to
the conduct of the parties [@sproule]. Because there is no express
contract in the present circumstances, a court would immediately turn
to the second branch of the analysis, which was described in @hayes as
follows:

> [It] requires the court to enquire into whether the conduct of the
  parties during the currency of their joint project constituted a
  partnership relationship notwithstanding their contrary intention
  and the provisions of their agreement (at 123).

The parties in @hayes did not meet the "business in common with a view
to profit" test.
```

Command:

    pandoc sample.md --bibliography bibliography.yaml --csl minimal.csl -o sample.org

Output:

```
The leading case in B.C. on the general test for the existence of a
partnership is that of (/Hayes v British Columbia Television
Broadcasting System Ltd/ (1992), 74 BCLR (2d) 120 (CA) [/Hayes/]). In
determining whether a partnership has formed, the meaning of the words
"carrying on business in common with a view of profit" should be
considered (/ibid/).

The parties must intend a partnership to form (/Sproule v McConnell/,
[1925] 1 DLR 982 (Sask CA) [/Sproule/]). The analysis used to discern
the intention of the parties is two-pronged. A court will first review
the agreement between the parties, then will look to the conduct of the
parties (/ibid/). Because there is no express contract in the present
circumstances, a court would immediately turn to the second branch of
the analysis, which was described in (/Hayes/) as follows:

#+BEGIN_QUOTE
  [It] requires the court to enquire into whether the conduct of the
  parties during the currency of their joint project constituted a
  partnership relationship notwithstanding their contrary intention and
  the provisions of their agreement (at 123).
#+END_QUOTE

The parties in /ibid/ did not meet the "business in common with a view
to profit" test.
```

# Issue

The first appearance of Hayes is `@hayes`, so there should be no enclosing parentheses, but there are.

Later, it should not have parentheses in `which was described in @hayes as follows`, but it does.

It properly doesn't have parentheses when used as a mention later: `the parties in @hayes did not meet` (although, I don't want mentions to be turned into "ibid", but that's a separate issue).

----------
Is this a bug? If not, I'd appreciate any help using this feature properly. Thanks!

**Comment by jgm** [comment] 2018-07-19 17:07
Not sure without further investigation, but this feature does work with other CSL files.
You might compare your CSL to the default chicago-author-date.csl, to see what might be different.

**Comment by sanchom** [comment] 2018-07-19 17:16
This is the `citation` section of `chicago-author-date.csl`:

```
<citation et-al-min="4" et-al-use-first="1" disambiguate-add-year-suffix="true" disambiguate-add-names="true" disambiguate-add-givenname="true" givenname-disambiguation-rule="primary-name" collapse="year">
    <layout prefix="(" suffix=")" delimiter="; ">
      <group delimiter=", ">
        <choose>
          <if variable="issued accessed" match="any">
            <group delimiter=" ">
              <text macro="contributors-short"/>
              <text macro="date-in-text"/>
            </group>
          </if>
          <!---comma before forthcoming and n.d.-->
          <else>
            <group delimiter=", ">
              <text macro="contributors-short"/>
              <text macro="date-in-text"/>
            </group>
          </else>
        </choose>
        <text macro="point-locators"/>
      </group>
    </layout>
</citation>
```

It has some more complicated parameters than mine related to disambiguation, but I don't see how those would be relevant to this behavior. The layout element is identical. Then, both `chicago-author-date.csl` and mine have a `<choose>` element with some `<group>` elements inside. Nothing remarkable is different between the two.

Are there any known limitations on what CSL this feature is intended to work with?

**Comment by jgm** [comment] 2018-07-19 17:17
The bare `@id` form is for "author-in-text" citations.  I suspect that the issue is your case is that your references lack an author field.

**Comment by sanchom** [comment] 2018-07-19 17:22
Oh, interesting. Would you be against extending this to work for any "in-text" citation? That is, strip the parentheses regardless of whether there is an author field, and let the CSL specify the form to use if it's a subsequent mention? I'm looking for a way to get subsequent mentions to use a short-form in both the `[@id]` and `@id` forms.

Or would you recommend that I just exclusively use the `[@id]` form, remove the parentheses affixes from the CSL, and place the parentheses by hand in the source markdown?

**Comment by njbart** [comment] 2018-07-19 20:55
That would be https://github.com/jgm/pandoc-citeproc/issues/136.

**Comment by jgm** [comment] 2018-10-12 21:58
Closing in favor of #136

**Closed by jgm** 2018-10-12 21:58 UTC
