### ISSUE TITLE
chicago-fullnote-bibliography, "speech": Extra comma after title

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#45] opened 2014-05-24 10:38 UTC
Using chicago-fullnote-bibliography, "speech" items are rendered with an extra comma after the title in the notes (in the bibliography, they look ok). – Zotero, using the very same csl style, does not insert a comma. – Any idea what's going on here?

Example, content from CMoS, 16e, 14.226:

```
pandoc -s -F pandoc-citeproc -t plain <<EOT

Foo [@item1]. Bar [@item2].

# References {-}

---
csl: chicago-fullnote-bibliography.csl
references:
- title-short: Early violent death in delinquent youth
  author:
  - family: Teplin
    given: Linda A.
  - family: McClelland
    given: Gary M.
  - family: Abram
    given: Karen M.
  - family: Washburn
    given: Jason J.
  id: item2
  issued:
    date-parts:
    - - 2005
      - 3
  title: 'Early violent death in delinquent youth: A prospective longitudinal study'
  type: speech
  genre: paper
  event: Annual Meeting of the American Psychology-Law Society
  event-place: La Jolla, CA

- author:
  - family: "D’Erasmo"
    given: Stacy
  id: item1
  issued:
    date-parts:
    - - 2000
      - 4
      - 26
  title: The craft and career of writing
  type: speech
  genre: lecture
  event-place: Northwestern University, Evanston, IL
...
EOT
```

Output:

```
Foo.[^1] Bar.[^2]

References {#references .unnumbered}
==========

D’Erasmo, Stacy. “The Craft and Career of Writing.” Lecture,
Northwestern University, Evanston, IL, April 26, 2000.

Teplin, Linda A., Gary M. McClelland, Karen M. Abram, and Jason J.
Washburn. “Early Violent Death in Delinquent Youth: A Prospective
Longitudinal Study.” Paper presented at the Annual Meeting of the
American Psychology-Law Society, La Jolla, CA, March 2005.

[^1]: Stacy D’Erasmo, “The Craft and Career of Writing,” (lecture,
    Northwestern University, Evanston, IL, April 26, 2000).

[^2]: Linda A. Teplin et al., “Early Violent Death in Delinquent Youth:
    A Prospective Longitudinal Study,” (paper presented at the Annual
    Meeting of the American Psychology-Law Society, La Jolla, CA, March
    2005).
```

Expected:

```
[^1]: Stacy D’Erasmo, “The Craft and Career of Writing” (lecture,
    Northwestern University, Evanston, IL, April 26, 2000).

[^2]: Linda A. Teplin et al., “Early Violent Death in Delinquent Youth:
    A Prospective Longitudinal Study” (paper presented at the Annual
    Meeting of the American Psychology-Law Society, La Jolla, CA, March
    2005).
```

**Comment by jgm** [comment] 2018-01-03 20:52
Is there something in the style that tells it to omit the comma, or is there a global CSL rule (or citeproc-js rule?) that simplifies `, (` to ` (`?

**Comment by adam3smith** [comment] 2018-01-04 16:30
There shouldn't be a comma there according to the style: `title-note` and `issue-note-join-with-space` are in a group with `delimiter=" "` so no special rules/omissions in place (nor would they be appropriate: `, " (` could very reasonably occur in a style.

**Comment by jgm** [comment] 2018-01-04 18:35
I'm a bit confused about how this is supposed to work.  The
issue-note-join-with-space macro only seems to affect
type="article-journal bill legislation legal_case manuscript
thesis", so why would it be triggered in this case (for a
speech)?

+++ Sebastian Karcher [Jan 04 18 16:30 ]:

**Comment by adam3smith** [comment] 2018-01-04 18:46
because of the `match="any"` it would be triggered if _any_ of the conditions are met, which include the presence of a `publisher` or `publisher-place` variable. (To simplify this, `<if type="article" variable="publisher" match="any">` is true for items that are _either_ articles _or_ have a publisher). 

I haven't tested, but I'd guess you're already handling this correctly in pandoc but the variable isn't in the YML data @njbart is using (but it would be in analogous Zotero data because Zotero's "Presentation" exports place as `publisher-place`).

**Comment by jgm** [comment] 2018-01-04 19:11
@njbart's test case is given above, so you can see that we have event-place but not publisher-place.

Actually, with up to date chicago-fullnote-bibliography.csl, I get slightly different output from the output @njbart reported above:
```
Foo.[1] Bar.[2]



REFERENCES


D’Erasmo, Stacy. “The Craft and Career of Writing.” Lecture,
Northwestern University, Evanston, IL, April 26, 2000.

Teplin, Linda A., Gary M. McClelland, Karen M. Abram, and Jason J.
Washburn. “Early Violent Death in Delinquent Youth: A Prospective
Longitudinal Study.” Paper presented at the Annual Meeting of the
American Psychology-Law Society, La Jolla, CA, March 2005.

[1] Stacy D’Erasmo, “The Craft and Career of Writing,” (Northwestern
University, Evanston, IL, April 26, 2000).

[2] Linda A. Teplin et al., “Early Violent Death in Delinquent Youth: A
Prospective Longitudinal Study,” (Annual Meeting of the American
Psychology-Law Society, La Jolla, CA, March 2005).
```
Note that the genre no longer appears in the footnotes (though it appears still in the bibliography). I assume this is due to a change in the style?  Still, we get the superfluous comma.

Sure enough, though:  if you add "event" to `<if type="...` in `issue-note-join-with-comma` and `issue-note-join-with-space` (or add `event-place` to the `variable` attribute in both places), then the superfluous comma disappears.  So I think you diagnosed this correctly.  It looks like this is not a bug in pandoc-citeproc, then, but perhaps a bug in the csl style?  @njbart any thoughts?

**Comment by njbart** [comment] 2018-01-04 19:36
> … the genre no longer appears …

That’s a style issue (see https://forums.zotero.org/discussion/69698/style-error-chicago-fullnote-bibliography-csl-presentation-does-not-output-type) that is going to be fixed.

Apart from that, @adam3smith’s explanation is convincing: Zotero maps the GUI “Place” field to *both* `event-place` and `publisher-place` (a somewhat problematic practice, but that’s moot for the moment …), so citeproc-js sees a non-empty `publisher-place`, triggering the use of the `issue-note-join-with-space` macro, i.e., no comma – while in my example, pandoc-citeproc sees an empty `publisher-place`, leading to the `issue-note-join-with-comma` macro being used.

Of course there’s nothing wrong with using `event-place` only in the input data (on the contrary, it’s much cleaner and clearer), and if I understand @adam3smith correctly, he is going to try and fix the style so that `event-place` alone will be sufficient to trigger the use of `issue-note-join-with-space` instead of `issue-note-join-with-comma`.

**Comment by adam3smith** [comment] 2018-01-04 19:44
agree, sorry if that wasn't clear. This is a style bug that doesn't manifest with Zotero due to Zotero's field mapping ideosyncracies, and we'll  fix it. Chicago has so many moving parts that it always takes a bit longer to fix, but shouldn't be too hard here.

**Comment by jgm** [comment] 2018-01-04 19:53
Glad we got to the bottom of it. Closing this issue, then!

**Closed by jgm** 2018-01-04 19:53 UTC
Labels: bug
