### ISSUE TITLE
pandoc-citeproc-0.7.3.1 test suite failure

### ISSUE THREAD

**Issue by peti** [jgm/pandoc-citeproc#172] opened 2015-09-22 08:39 UTC
I'm seeing spurious test suite failures from `pandoc-citeproc-0.7.3.1`. I'm citing from http://hydra.cryp.to/build/1304494/log/raw:

```
Running 1 test suites...
Test suite test-pandoc-citeproc: RUNNING...
[number-of-volumes.in.native] test-pandoc-citeproc: fd:6: hClose: resource vanished (Broken pipe)
Test suite test-pandoc-citeproc: FAIL
```

I suppose there's a race condition somewhere?

**Comment by jgm** [comment] 2015-09-22 16:48
I'm not sure what is going on here.

I use travis for CI testing, and haven't seen anything like
this on the travis builds.

You might try 0.7.4.

+++ Peter Simons [Sep 22 15 01:39 ]:

**Comment by peti** [comment] 2015-10-18 19:19
pandoc-citeproc-0.7.4 has the same issue: http://hydra.cryp.to/build/1338884/log/raw.

**Comment by jgm** [comment] 2015-10-19 04:34
Ok, here's a bit of background on how the test suite works.  It uses this code to try to find the pandoc-citeproc executable, relative to the test program (test-pandoc-citeproc), and then run it as a pipe:

``` haskell
  testProgPath <- getExecutablePath
  let pandocCiteprocPath = takeDirectory testProgPath </> ".." </>
        "pandoc-citeproc" </> "pandoc-citeproc"
  (ec, jsonOut, errout) <- pipeProcess
                     (Just [("LANG","en_US.UTF-8"),("HOME",".")])
                     pandocCiteprocPath
                     [] jsonIn
```
If I had to guess, I'd guess that something peculiar about your build environment is breaking some assumption I'm making here.  (Again, I can't reproduce this on any of the build environments I use regularly.)

**Comment by peti** [comment] 2015-10-19 09:04
Well, the test won't fail every time we run it on our hardware either. It fails spuriously, which is why I think it's a race condition / timing issue.

**Comment by jgm** [comment] 2015-10-19 16:38
Do you recall what percent of the time it fails in this way?

Now I'm thinking that the issue may be in Text.Pandoc.Process.pipeProcess, which we use to run pandoc-citeproc and collect its output.  Its logic is mostly copied directly from System.Process.readProcessWithExitCode, and I've never seen this problem arising from its use in pandoc.

However, it's going to be hard to verify this or debug further without being able to reproduce the problem on my own.

**Comment by peti** [comment] 2015-10-23 08:39
> Do you recall what percent of the time it fails in this way?

Unfortunately, I don't know that.

**Comment by juhp** [comment] 2015-11-15 13:37
It would be nice to have such stats from Stackage, unfortunately we don't keep logs around yet.

It seems to pass frequently though.

**Comment by jgm** [comment] 2017-12-15 22:17
Closing unless there's new information.

**Closed by jgm** 2017-12-15 22:17 UTC
