### ISSUE TITLE
Nested <group> (with "first-reference-note-number" in it) ignored in 'zeitschrift-fur-kunstgeschichte.csl'

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [jgm/pandoc-citeproc#352] opened 2018-10-13 14:24 UTC
After https://github.com/jgm/pandoc-citeproc/commit/c0c4f0665a65ff1561c3f7dc1fe98c6bac302c4f, to my knowledge there remains only one difference in the output of two would-be-identical docx documents generated by pandoc & pandoc-citeproc and LibreOffice writer & Zotero:

After the first (and full) citation of a given work, on subsequent occasions the style prints a short citation form with authors' names and year (unless it's an 'ibid'). In addition to that, it points, in parentheses, to the footnote where the cited work was cited for the first time in the document.
Such a citation footnote would look like
`Knuth 1986 (as note 1).`

In the CSL style's code, this should be achieved in [lines 151](https://github.com/citation-style-language/styles/blob/9e60a404fe3628ae1b8d1c455118d61db19d0f30/zeitschrift-fur-kunstgeschichte.csl#L151)-154:
```
<group delimiter=" " prefix="(" suffix=")">
  <text term="note"/>
  <text variable="first-reference-note-number"/>
</group>
```
In pandoc-generated document, none of the elements listed in this group appear, and the footnote from above will be
`Knuth 1986.`,
which means that the other elements in the `<group>` one level further up above _are_ being printed. So I suppose it is the inner group as a whole that poses a problem?

(I myself do not want to use this specific feature, and in my use case I would edit the style and take it out if it worked correctly. But since it appears to be a bug, I thought documenting it here couldn't hurt.)

**Comment by jgm** [comment] 2018-10-13 14:43
This is a duplicate of #31 - first-reference-number isn't yet supported.

**Closed by jgm** 2018-10-13 14:43 UTC

**Comment by jgm** [comment] 2018-10-14 21:47
Should now be fixed...
