### ISSUE TITLE
Links are only added to the cited year and not the entire citation

### ISSUE THREAD

**Issue by CxRes** [jgm/pandoc-citeproc#398] opened 2019-04-17 10:09 UTC
With `--metadata link-citation=true` option I get a html output where only the year in the citations are linked to the references created at the end (instead of the entire citation). 

Ditto in PDF!!!!

With:
```sh
pandoc -F pandoc-citeproc --metadata link-citations=true -o foo.html foo.md
```

and `foo.md`:
```md
Hello [@engelbart1962]
```

I get an output of the form:
```html
<body>
  <p>Hello 
    <span class="citation" data-cites="engelbart1962">(Engelbart <a href="#ref-engelbart1962">1962</a>)</span>
  </p>
  ...
</body>
``` 

One would expect:
```html
<body>
  <p>Hello 
    <span class="citation" data-cites="engelbart1962">(<a href="#ref-engelbart1962">Engelbart 1962</a>)</span>
  </p>
  ...
</body>
``` 

Pandoc 2.1.3
Citeproc 0.14.2
OS: Windows 10 x64

**Comment by jgm** [comment] 2019-04-17 15:19
Duplicate of #268

**Closed by jgm** 2019-04-17 15:19 UTC
