### ISSUE TITLE
Different bibliography output to zotero using the same csl and .bib

### ISSUE THREAD

**Issue by gepcel** [jgm/pandoc-citeproc#327] opened 2018-03-28 08:06 UTC
I used pandoc to convert a simple `md` file to `pdf`. The output bibliography was like (copied from the pdf):

`[1] 李轶, 于旭, 孙明, 等. 辽东湾海域底栖动物次级⽣产⼒研究及⽣境适宜性评价 [J]. ⽔产科
学, 2017(06): 728–734.`

And here is the bibliography generated by zotero:

`[1]李轶平, 于旭光, 孙明等. 辽东湾海域底栖动物次级生产力研究及生境适宜性评价[J]. 水产科学, 2017(06): 728–734.`

Note that the authors names are shortened, only two Chinese characters left. The character `等` is like the Chinese version of `et al.` There's also difference in handling of the last name and `et al.`. I'm not sure what's the right way, I actually like the pandoc way of handling the last name and `et al.`, but not the way it strip the name to 2 characters. 

**All materials used**

* Command I used:

 `pandoc -o a.pdf --template=c:/python/lib/default.tex --filter pandoc-citeproc --pdf-engine=xelatex a.md --bibliography ./my.bib --csl=./chinese-gb7714-2005-numeric.csl`

* The `a.md` file:

```txt
I referenced something here [@LiLiaoDongWanHaiYuDiQiDongWuCiJiShengChanLiYanJiuJiShengJingGuaYiXingPingJie2017]
```

* The `my.bib` file (exported from zotero):
```
@article{LiLiaoDongWanHaiYuDiQiDongWuCiJiShengChanLiYanJiuJiShengJingGuaYiXingPingJie2017,
  langid = {中文;},
  title = {辽东湾海域底栖动物次级生产力研究及生境适宜性评价},
  issn = {1003-1111},
  url = {http://kns.cnki.net/kns/detail/detail.aspx?QueryID=4&CurRec=4&recid=&FileName=CHAN201706006&DbName=CJFDLAST2018&DbCode=CJFQ&yx=Y&pr=&URLID=21.1110.S.20171129.1725.006},
  abstract = {为了解辽东湾海域底栖动物次级生产力水平和时空分布特点,根据2007年的4月和10月辽东湾海域大型底栖动物调查数据,运用Brey经验公式计算大型底栖动物次级生产力和P/B值,并结合海洋生物指数方法对辽东湾海域进行生境适宜性评价。分析结果表明,该海域大型底栖动物年平均次级生产力为5.59g/(m\textasciitilde{}2·年),年平均P/B值为3.16,辽东湾大型底栖动物次级生产力空间分布呈现出自沿岸向中部递增的趋势,P/B值空间分布与底栖动物次级生产力相反,呈现出自沿岸向中部递减的趋势,群落组成中以个体小、生活史短、代谢快的底栖动物为主。},
  issue = {06},
  journaltitle = {水产科学},
  urldate = {2018-03-27},
  date = {2017},
  pages = {728--734},
  keywords = {次级生产力,大型底栖动物,海洋生物指数方法,AMBI,macrozoobenthos,P/B value,P/B值,secondary productivity},
  author = {李, 轶平 and 于, 旭光 and 孙, 明 and 郭, 栋 and 段, 妍 and 董, 婧}
}
```

* The `csl` file was from [citation-style-language/styles/](https://github.com/citation-style-language/styles/blob/master/chinese-gb7714-2005-numeric.csl)

**How to get this?**

`[1]李轶平, 于旭光, 孙明, 等. 辽东湾海域底栖动物次级生产力研究及生境适宜性评价[J]. 水产科学, 2017(06): 728–734.`

**Version**
pandoc 2.1.2
pandoc-citeproc 0.14.1.5

**Comment by njbart** [comment] 2018-03-28 12:26
I don't know Chinese at all, but it seems none of the names in your biblatex `author` field are longer than two characters, so I’m wondering whether it’s even possible to get the output you report as being “generated by zotero” – which seems to contain three-character names – from this biblatex input. Could you double-check whether the content of the author field(s) of your test case in Zotero and biblatex is exactly the same?

**Comment by gepcel** [comment] 2018-03-28 14:12
@njbart  Sorry for the inconvenience of Chinese. In this example, the names of all authors should be `李轶平 , 于旭光, 孙明, 郭栋, 段妍, 董婧`.  In Chinese, `李轶平` should never be shortened as `李轶`. The format in `my.bib`  may be zotero's way of handling last and first name like: `李, 轶平`, using `and` to seperate authors, comma `,` to seperate last and first names. 

But I get your point, after some testing, if I delete all the commas between author names in `my.bib` file, I will get the result I want. But should `zotero` export bib without commas between last and first names (and how?), or should pandoc-citeproc recognize the commas  like zotero? I'm not sure.

**Comment by njbart** [comment] 2018-03-28 18:36
Ok, two more questions: How do you enter Chinese names in Zotero – do you use the “two fields” (i.e., last, first) or the “single field” option? And how do you export to biblatex – Zotero’s own exporter, or Better Bib(La)TeX?

**Comment by gepcel** [comment] 2018-03-28 23:20
Answer to Q1: Names were stored in "two fields". These informations are auto captured from an [Chinese website](http://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFQ&dbname=CJFDLAST2018&filename=CHAN201706006&v=MTg4ODRSTEtmWk9SbUZpN2xXN3ZJSmlYS1lMRzRIOWJNcVk5RllvUjhlWDFMdXhZUzdEaDFUM3FUcldNMUZyQ1U=), with a "Save to Zotero" extension for chrome.

Answer to Q2: I actually tried both "biblatex" and "better biblatex". Different cite key, but same results.

**Comment by njbart** [comment] 2018-03-29 07:03
If names are entered in two fields (i.e., last, first), then exporting these to bibtex/biblatex as `author = {Last, First}` certainly seems correct.

Anyhow, I can reproduce the differing behaviour of Zotero and pandoc-citeproc with your item. 

@fbennett, if you’re listening: Are you aware of anything in the CSL specs pandoc-citeproc may have overlooked, or any undocumented extensions in citeproc-js that could explain these differences in name formatting?

**Comment by fbennett** [comment] 2018-03-29 07:26
There is some (old) code in `citeproc-js` that sniffs at Unicode character sets to guess at name-handling conventions and a few other things. The regexps are here: https://github.com/Juris-M/citeproc-js/blob/master/src/load.js#L542

**Comment by njbart** [comment] 2018-03-29 10:53
@fbennett: Many thanks, that’s helpful. Would you happen to recall the exact rule that would be appropriate for Chinese names? @gepcel seems to expect `LastFirst` (without a comma within an individual’s name; not sure about spaces, though).

**Comment by fbennett** [comment] 2018-03-29 12:12
It would be LastFirst, no spaces. I have seen publications in Japanese that apply a kind of first-name abbreviation, written something like 梅【健】(for "Ume [Ken]"-jirō). That may be peculiar to Japan though. I think full-name rendering as @gepcel says is more common in CJK jurisdictions.

The regexp in citeproc-js captures scripts associated with the European-style given-name/family-name ordering---I ended up treating that as the exception. I'm not quite sure what it catches (should have made a note!). Latin-1, Cyrillic and Persian are the ones I can remember off the top of my head. For an opt-in approach for Chinese or CJK names, this [StackOverflow page](https://stackoverflow.com/questions/19899554/unicode-range-for-japanese) gives some hints that might be a useful starting point for working out a range.

**Comment by njbart** [comment] 2018-03-30 11:38
@fbennett – no problem, thanks. 

If I understand this correctly now, pandoc-citeproc does omit the comma, but not the space between `Last` and `First`. Inserting a space looks like a pandoc-citeproc bug: though the style uses [`sort-separator=" "`](https://github.com/citation-style-language/styles/blob/master/chinese-gb7714-2005-numeric.csl#L22), no space should be inserted in a Chinese name since the [CSL specs](http://docs.citationstyles.org/en/1.0.1/specification.html#name) say, “As is the case for `name-as-sort-order`, this attribute [`sort-separator`] only affects names written in the latin or Cyrillic alphabets.”

On the other hand, the same element of the style also uses [initialize-with=" "](https://github.com/citation-style-language/styles/blob/master/chinese-gb7714-2005-numeric.csl#L22). Here, I can’t find any qualification in the CSL specs limiting this to Latin or Cyrillic alphabets, so pandoc-citeproc, rendering the equivalent of `Last F`, seems to follow the specs, whereas citeproc-js does not (though if the rule that Chinese first names should never be abbreviated is sound, it’s probably the specs [and pandoc-citeproc] that should be fixed rather than citeproc-js).

Finally, the way Zotero/citeproc-js outputs the equivalent of “et al.” (attached, sort of, to the last author’s name) does look a bit odd indeed. Not knowing Chinese, I have no way of telling whether that’s actually incorrect, but with `delimiter-precedes-last="always"` set in the style, and, apparently, nothing limiting this to Latin or Cyrillic alphabets, it seems that pandoc-citeproc is following the CSL specs - though it’s be interesting to know why citeproc-js outputs “et al.” differently.

**Comment by gepcel** [comment] 2018-03-30 12:20
@njbart 
As to the way Zotero add "et al.", I think pandoc-citeproc did it right. Like (the right way):

LastFirst, LastFirst, LastFirst, 等. Title of Article. ........something else.

“等” is the Chinese of "et al.". There should be a comma and a space between the third author and "等".

About these kind of stuff, there is a standardization about "Rules for bibliographic references and citations to information resources": GB/T 7714-2015 in Chinese. I can send you a copy via email (haven't figure out how to upload this) if you want.

**Comment by fbennett** [comment] 2018-03-30 13:01
Can make that adjustment in citeproc-js.

@njbart Would you be able to open a discussion on xbiblio-devel, about the spec and processor behavior? I'll be full up on another task for the next couple of days at least, and probably wouldn't be able to explain things clearly.

**Comment by fbennett** [comment] 2018-03-30 13:03
@gepcel No need, very happy to take your word on it. Commas (at least not ASCII commas) are not normally a feature of Japanese typography, but if they are used in the Chinese domain we can turn them on.

**Comment by gepcel** [comment] 2018-03-30 13:51
@fbennett , Sorry, my English is not good enough to understand much of these conversions. In case I'm not suggesting (or what you think I'm suggesting) some wrong ideas, it's better to let some body good at this to verify, or would you please double check this from more sources other than me, before any conclusions.

I'm not that good at English, very very sorry for the inconvenience.

**Comment by gepcel** [comment] 2018-05-10 12:58
Found a [very good style](https://github.com/zepinglee/gbt7714-bibtex-style) that accomplish GB/T 7714-2015 in Chinese, with many reproduceable examples. And the author of this is more reliable and professional than me.

**Closed** 2018-10-13 00:50 UTC
